CREATE TABLE IF NOT EXISTS `pessoa` (
  `id_pessoa` INT(11) NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(60) NULL DEFAULT NULL,
  `cpf` VARCHAR(11) NULL DEFAULT NULL,
  `data_registro` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`id_pessoa`));